# ==========================================
# MOFFAT BAY MARINA DATABASE
# ==========================================

# db.host=localhost
# db.port=3306
# db.name=moffat_bay
# db.user=root
# db.password=

db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/moffat_bay
db.username=root
db.password=